/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as PreConsultationRouteImport } from './routes/pre-consultation'
import { Route as RandevouRouteImport } from './routes/randevou'
import { Route as ServicesRouteImport } from './routes/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const PreConsultationRoute = PreConsultationRouteImport.update({
  id: '/pre-consultation',
  path: '/pre-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const RandevouRoute = RandevouRouteImport.update({
  id: '/randevou',
  path: '/randevou',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/destinations': typeof DestinationsRoute
  '/pre-consultation': typeof PreConsultationRoute
  '/randevou': typeof RandevouRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/destinations': typeof DestinationsRoute
  '/pre-consultation': typeof PreConsultationRoute
  '/randevou': typeof RandevouRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/destinations': typeof DestinationsRoute
  '/pre-consultation': typeof PreConsultationRoute
  '/randevou': typeof RandevouRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/destinations'
    | '/pre-consultation'
    | '/randevou'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/destinations'
    | '/pre-consultation'
    | '/randevou'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/destinations'
    | '/pre-consultation'
    | '/randevou'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  DestinationsRoute: typeof DestinationsRoute
  PreConsultationRoute: typeof PreConsultationRoute
  RandevouRoute: typeof RandevouRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-consultation': {
      id: '/pre-consultation'
      path: '/pre-consultation'
      fullPath: '/pre-consultation'
      preLoaderRoute: typeof PreConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randevou': {
      id: '/randevou'
      path: '/randevou'
      fullPath: '/randevou'
      preLoaderRoute: typeof RandevouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  DestinationsRoute: DestinationsRoute,
  PreConsultationRoute: PreConsultationRoute,
  RandevouRoute: RandevouRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
